version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - /c/Users/HP/Desktop/data:/data/db
        command: npm run dev
