services:
    auth-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: auth-service-dev
        ports:
            - "5501:5501"
        working_dir: /usr/src/app
        develop:
            watch:
                - action: sync
                  path: .
                  target: /usr/src/app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json
                - action: rebuild
                  path: .env
        env_file:
            - .env
        environment:
            - NODE_ENV=development
        stdin_open: true
        tty: true
        restart: "no"
